# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Arunpillaii\Documents\maya\scripts\controlMaker\resources\controlMakerWidget.ui'
#
# Created: Thu Jan 11 00:40:35 2018
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_ControlMakerWin(object):
    def setupUi(self, ControlMakerWin):
        ControlMakerWin.setObjectName("ControlMakerWin")
        ControlMakerWin.resize(363, 681)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ControlMakerWin)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.main_VL = QtWidgets.QVBoxLayout()
        self.main_VL.setSpacing(5)
        self.main_VL.setObjectName("main_VL")
        self.make_GB = QtWidgets.QGroupBox(ControlMakerWin)
        self.make_GB.setObjectName("make_GB")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.make_GB)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.name_HL = QtWidgets.QHBoxLayout()
        self.name_HL.setObjectName("name_HL")
        self.name_LB = QtWidgets.QLabel(self.make_GB)
        self.name_LB.setObjectName("name_LB")
        self.name_HL.addWidget(self.name_LB)
        self.name_LE = QtWidgets.QLineEdit(self.make_GB)
        self.name_LE.setObjectName("name_LE")
        self.name_HL.addWidget(self.name_LE)
        self.nameGroup_CB = QtWidgets.QCheckBox(self.make_GB)
        self.nameGroup_CB.setChecked(True)
        self.nameGroup_CB.setObjectName("nameGroup_CB")
        self.name_HL.addWidget(self.nameGroup_CB)
        self.verticalLayout_3.addLayout(self.name_HL)
        self.makeType_HL = QtWidgets.QHBoxLayout()
        self.makeType_HL.setObjectName("makeType_HL")
        self.type_LB = QtWidgets.QLabel(self.make_GB)
        self.type_LB.setObjectName("type_LB")
        self.makeType_HL.addWidget(self.type_LB)
        self.type_HL = QtWidgets.QHBoxLayout()
        self.type_HL.setObjectName("type_HL")
        self.type2D_RB = QtWidgets.QRadioButton(self.make_GB)
        self.type2D_RB.setChecked(True)
        self.type2D_RB.setObjectName("type2D_RB")
        self.type_HL.addWidget(self.type2D_RB)
        self.type3D_RB = QtWidgets.QRadioButton(self.make_GB)
        self.type3D_RB.setObjectName("type3D_RB")
        self.type_HL.addWidget(self.type3D_RB)
        self.makeType_HL.addLayout(self.type_HL)
        self.controlType_CB = QtWidgets.QComboBox(self.make_GB)
        self.controlType_CB.setObjectName("controlType_CB")
        self.makeType_HL.addWidget(self.controlType_CB)
        self.makeType_HL.setStretch(2, 1)
        self.verticalLayout_3.addLayout(self.makeType_HL)
        self.createControl_BN = QtWidgets.QPushButton(self.make_GB)
        self.createControl_BN.setObjectName("createControl_BN")
        self.verticalLayout_3.addWidget(self.createControl_BN)
        self.main_VL.addWidget(self.make_GB)
        self.edit_GB = QtWidgets.QGroupBox(ControlMakerWin)
        self.edit_GB.setObjectName("edit_GB")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.edit_GB)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.translation_GB = QtWidgets.QGroupBox(self.edit_GB)
        self.translation_GB.setAlignment(QtCore.Qt.AlignCenter)
        self.translation_GB.setObjectName("translation_GB")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.translation_GB)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.transOrientation_HL = QtWidgets.QHBoxLayout()
        self.transOrientation_HL.setObjectName("transOrientation_HL")
        self.transOrientation_LB = QtWidgets.QLabel(self.translation_GB)
        self.transOrientation_LB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.transOrientation_LB.setObjectName("transOrientation_LB")
        self.transOrientation_HL.addWidget(self.transOrientation_LB)
        self.transOrientation_CB = QtWidgets.QComboBox(self.translation_GB)
        self.transOrientation_CB.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.transOrientation_CB.setObjectName("transOrientation_CB")
        self.transOrientation_CB.addItem("")
        self.transOrientation_CB.addItem("")
        self.transOrientation_CB.addItem("")
        self.transOrientation_HL.addWidget(self.transOrientation_CB)
        self.transAxis_LB = QtWidgets.QLabel(self.translation_GB)
        self.transAxis_LB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.transAxis_LB.setObjectName("transAxis_LB")
        self.transOrientation_HL.addWidget(self.transAxis_LB)
        self.transAxis_CB = QtWidgets.QComboBox(self.translation_GB)
        self.transAxis_CB.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.transAxis_CB.setObjectName("transAxis_CB")
        self.transAxis_CB.addItem("")
        self.transAxis_CB.addItem("")
        self.transAxis_CB.addItem("")
        self.transOrientation_HL.addWidget(self.transAxis_CB)
        self.verticalLayout_5.addLayout(self.transOrientation_HL)
        self.transValue_HL_2 = QtWidgets.QHBoxLayout()
        self.transValue_HL_2.setObjectName("transValue_HL_2")
        self.transValue_LB = QtWidgets.QLabel(self.translation_GB)
        self.transValue_LB.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.transValue_LB.setObjectName("transValue_LB")
        self.transValue_HL_2.addWidget(self.transValue_LB)
        self.transValue_DS = QtWidgets.QDoubleSpinBox(self.translation_GB)
        self.transValue_DS.setAlignment(QtCore.Qt.AlignCenter)
        self.transValue_DS.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.transValue_DS.setDecimals(2)
        self.transValue_DS.setProperty("value", 1.0)
        self.transValue_DS.setObjectName("transValue_DS")
        self.transValue_HL_2.addWidget(self.transValue_DS)
        self.transReverse_CB = QtWidgets.QCheckBox(self.translation_GB)
        self.transReverse_CB.setObjectName("transReverse_CB")
        self.transValue_HL_2.addWidget(self.transReverse_CB)
        self.transValue_HL_2.setStretch(1, 1)
        self.verticalLayout_5.addLayout(self.transValue_HL_2)
        self.translate_BN = QtWidgets.QPushButton(self.translation_GB)
        self.translate_BN.setObjectName("translate_BN")
        self.verticalLayout_5.addWidget(self.translate_BN)
        self.verticalLayout_4.addWidget(self.translation_GB)
        self.rotation_GB = QtWidgets.QGroupBox(self.edit_GB)
        self.rotation_GB.setAlignment(QtCore.Qt.AlignCenter)
        self.rotation_GB.setObjectName("rotation_GB")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.rotation_GB)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.orientation_HL = QtWidgets.QHBoxLayout()
        self.orientation_HL.setObjectName("orientation_HL")
        self.orientation_LB = QtWidgets.QLabel(self.rotation_GB)
        self.orientation_LB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.orientation_LB.setObjectName("orientation_LB")
        self.orientation_HL.addWidget(self.orientation_LB)
        self.orientation_CB = QtWidgets.QComboBox(self.rotation_GB)
        self.orientation_CB.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.orientation_CB.setObjectName("orientation_CB")
        self.orientation_CB.addItem("")
        self.orientation_CB.addItem("")
        self.orientation_HL.addWidget(self.orientation_CB)
        self.rotationAxis_LB = QtWidgets.QLabel(self.rotation_GB)
        self.rotationAxis_LB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rotationAxis_LB.setObjectName("rotationAxis_LB")
        self.orientation_HL.addWidget(self.rotationAxis_LB)
        self.rotationAxis_CB = QtWidgets.QComboBox(self.rotation_GB)
        self.rotationAxis_CB.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.rotationAxis_CB.setObjectName("rotationAxis_CB")
        self.rotationAxis_CB.addItem("")
        self.rotationAxis_CB.addItem("")
        self.rotationAxis_CB.addItem("")
        self.orientation_HL.addWidget(self.rotationAxis_CB)
        self.verticalLayout_7.addLayout(self.orientation_HL)
        self.transValue_HL = QtWidgets.QHBoxLayout()
        self.transValue_HL.setObjectName("transValue_HL")
        self.rotationValue_LB = QtWidgets.QLabel(self.rotation_GB)
        self.rotationValue_LB.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rotationValue_LB.setObjectName("rotationValue_LB")
        self.transValue_HL.addWidget(self.rotationValue_LB)
        self.rotationValue_DS = QtWidgets.QDoubleSpinBox(self.rotation_GB)
        self.rotationValue_DS.setAlignment(QtCore.Qt.AlignCenter)
        self.rotationValue_DS.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.rotationValue_DS.setDecimals(2)
        self.rotationValue_DS.setProperty("value", 90.0)
        self.rotationValue_DS.setObjectName("rotationValue_DS")
        self.transValue_HL.addWidget(self.rotationValue_DS)
        self.rotationReverse_CB = QtWidgets.QCheckBox(self.rotation_GB)
        self.rotationReverse_CB.setObjectName("rotationReverse_CB")
        self.transValue_HL.addWidget(self.rotationReverse_CB)
        self.rotationPivot_LB = QtWidgets.QLabel(self.rotation_GB)
        self.rotationPivot_LB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rotationPivot_LB.setObjectName("rotationPivot_LB")
        self.transValue_HL.addWidget(self.rotationPivot_LB)
        self.rotationPivot_CB = QtWidgets.QComboBox(self.rotation_GB)
        self.rotationPivot_CB.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.rotationPivot_CB.setObjectName("rotationPivot_CB")
        self.rotationPivot_CB.addItem("")
        self.rotationPivot_CB.addItem("")
        self.transValue_HL.addWidget(self.rotationPivot_CB)
        self.transValue_HL.setStretch(4, 1)
        self.verticalLayout_7.addLayout(self.transValue_HL)
        self.rotation_BN = QtWidgets.QPushButton(self.rotation_GB)
        self.rotation_BN.setObjectName("rotation_BN")
        self.verticalLayout_7.addWidget(self.rotation_BN)
        self.verticalLayout_4.addWidget(self.rotation_GB)
        self.scale_GB = QtWidgets.QGroupBox(self.edit_GB)
        self.scale_GB.setAlignment(QtCore.Qt.AlignCenter)
        self.scale_GB.setObjectName("scale_GB")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.scale_GB)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.scalePivot_HL = QtWidgets.QHBoxLayout()
        self.scalePivot_HL.setObjectName("scalePivot_HL")
        self.scalePivot_LB = QtWidgets.QLabel(self.scale_GB)
        self.scalePivot_LB.setAlignment(QtCore.Qt.AlignCenter)
        self.scalePivot_LB.setObjectName("scalePivot_LB")
        self.scalePivot_HL.addWidget(self.scalePivot_LB)
        self.scalePivot_CB = QtWidgets.QComboBox(self.scale_GB)
        self.scalePivot_CB.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.scalePivot_CB.setObjectName("scalePivot_CB")
        self.scalePivot_CB.addItem("")
        self.scalePivot_CB.addItem("")
        self.scalePivot_HL.addWidget(self.scalePivot_CB)
        self.sacleValue_LB = QtWidgets.QLabel(self.scale_GB)
        self.sacleValue_LB.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sacleValue_LB.setObjectName("sacleValue_LB")
        self.scalePivot_HL.addWidget(self.sacleValue_LB)
        self.scaleValue_DS = QtWidgets.QDoubleSpinBox(self.scale_GB)
        self.scaleValue_DS.setAlignment(QtCore.Qt.AlignCenter)
        self.scaleValue_DS.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.scaleValue_DS.setDecimals(2)
        self.scaleValue_DS.setProperty("value", 0.1)
        self.scaleValue_DS.setObjectName("scaleValue_DS")
        self.scalePivot_HL.addWidget(self.scaleValue_DS)
        self.scaleReverse_CB = QtWidgets.QCheckBox(self.scale_GB)
        self.scaleReverse_CB.setObjectName("scaleReverse_CB")
        self.scalePivot_HL.addWidget(self.scaleReverse_CB)
        self.verticalLayout_8.addLayout(self.scalePivot_HL)
        self.scaleValue_HL = QtWidgets.QHBoxLayout()
        self.scaleValue_HL.setObjectName("scaleValue_HL")
        self.scaleAxis_LB = QtWidgets.QLabel(self.scale_GB)
        self.scaleAxis_LB.setAlignment(QtCore.Qt.AlignCenter)
        self.scaleAxis_LB.setObjectName("scaleAxis_LB")
        self.scaleValue_HL.addWidget(self.scaleAxis_LB)
        self.scaleX_CB = QtWidgets.QCheckBox(self.scale_GB)
        self.scaleX_CB.setChecked(True)
        self.scaleX_CB.setObjectName("scaleX_CB")
        self.scaleValue_HL.addWidget(self.scaleX_CB)
        self.scaleY_CB = QtWidgets.QCheckBox(self.scale_GB)
        self.scaleY_CB.setChecked(True)
        self.scaleY_CB.setObjectName("scaleY_CB")
        self.scaleValue_HL.addWidget(self.scaleY_CB)
        self.scaleZ_CB = QtWidgets.QCheckBox(self.scale_GB)
        self.scaleZ_CB.setChecked(True)
        self.scaleZ_CB.setObjectName("scaleZ_CB")
        self.scaleValue_HL.addWidget(self.scaleZ_CB)
        self.verticalLayout_8.addLayout(self.scaleValue_HL)
        self.scale_BN = QtWidgets.QPushButton(self.scale_GB)
        self.scale_BN.setObjectName("scale_BN")
        self.verticalLayout_8.addWidget(self.scale_BN)
        self.verticalLayout_4.addWidget(self.scale_GB)
        self.mirror_GB = QtWidgets.QGroupBox(self.edit_GB)
        self.mirror_GB.setAlignment(QtCore.Qt.AlignCenter)
        self.mirror_GB.setObjectName("mirror_GB")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.mirror_GB)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.mirrorSearch_HL = QtWidgets.QHBoxLayout()
        self.mirrorSearch_HL.setObjectName("mirrorSearch_HL")
        self.search_LB = QtWidgets.QLabel(self.mirror_GB)
        self.search_LB.setObjectName("search_LB")
        self.mirrorSearch_HL.addWidget(self.search_LB)
        self.search_LE = QtWidgets.QLineEdit(self.mirror_GB)
        self.search_LE.setObjectName("search_LE")
        self.mirrorSearch_HL.addWidget(self.search_LE)
        self.replace_LB = QtWidgets.QLabel(self.mirror_GB)
        self.replace_LB.setObjectName("replace_LB")
        self.mirrorSearch_HL.addWidget(self.replace_LB)
        self.replace_LE = QtWidgets.QLineEdit(self.mirror_GB)
        self.replace_LE.setObjectName("replace_LE")
        self.mirrorSearch_HL.addWidget(self.replace_LE)
        self.verticalLayout_9.addLayout(self.mirrorSearch_HL)
        self.mirror_BN = QtWidgets.QPushButton(self.mirror_GB)
        self.mirror_BN.setObjectName("mirror_BN")
        self.verticalLayout_9.addWidget(self.mirror_BN)
        self.verticalLayout_4.addWidget(self.mirror_GB)
        self.main_VL.addWidget(self.edit_GB)
        self.verticalLayout_2.addLayout(self.main_VL)

        self.retranslateUi(ControlMakerWin)
        QtCore.QMetaObject.connectSlotsByName(ControlMakerWin)

    def retranslateUi(self, ControlMakerWin):
        ControlMakerWin.setWindowTitle(QtWidgets.QApplication.translate("ControlMakerWin", "Control Maker", None, -1))
        self.make_GB.setTitle(QtWidgets.QApplication.translate("ControlMakerWin", "MAKE", None, -1))
        self.name_LB.setText(QtWidgets.QApplication.translate("ControlMakerWin", "Name :", None, -1))
        self.nameGroup_CB.setText(QtWidgets.QApplication.translate("ControlMakerWin", "Group", None, -1))
        self.type_LB.setText(QtWidgets.QApplication.translate("ControlMakerWin", "Type :", None, -1))
        self.type2D_RB.setText(QtWidgets.QApplication.translate("ControlMakerWin", "2D", None, -1))
        self.type3D_RB.setText(QtWidgets.QApplication.translate("ControlMakerWin", "3D", None, -1))
        self.createControl_BN.setText(QtWidgets.QApplication.translate("ControlMakerWin", "Create", None, -1))
        self.edit_GB.setTitle(QtWidgets.QApplication.translate("ControlMakerWin", "EDIT", None, -1))
        self.translation_GB.setTitle(QtWidgets.QApplication.translate("ControlMakerWin", "TRANSLATION", None, -1))
        self.transOrientation_LB.setText(QtWidgets.QApplication.translate("ControlMakerWin", "Orientation :", None, -1))
        self.transOrientation_CB.setItemText(0, QtWidgets.QApplication.translate("ControlMakerWin", "World", None, -1))
        self.transOrientation_CB.setItemText(1, QtWidgets.QApplication.translate("ControlMakerWin", "Object", None, -1))
        self.transOrientation_CB.setItemText(2, QtWidgets.QApplication.translate("ControlMakerWin", "Local", None, -1))
        self.transAxis_LB.setText(QtWidgets.QApplication.translate("ControlMakerWin", "Axis :", None, -1))
        self.transAxis_CB.setItemText(0, QtWidgets.QApplication.translate("ControlMakerWin", "X", None, -1))
        self.transAxis_CB.setItemText(1, QtWidgets.QApplication.translate("ControlMakerWin", "Y", None, -1))
        self.transAxis_CB.setItemText(2, QtWidgets.QApplication.translate("ControlMakerWin", "Z", None, -1))
        self.transValue_LB.setText(QtWidgets.QApplication.translate("ControlMakerWin", "Value :", None, -1))
        self.transReverse_CB.setText(QtWidgets.QApplication.translate("ControlMakerWin", "Reverse", None, -1))
        self.translate_BN.setText(QtWidgets.QApplication.translate("ControlMakerWin", "Translate", None, -1))
        self.rotation_GB.setTitle(QtWidgets.QApplication.translate("ControlMakerWin", "ROTATION", None, -1))
        self.orientation_LB.setText(QtWidgets.QApplication.translate("ControlMakerWin", "Orientation :", None, -1))
        self.orientation_CB.setItemText(0, QtWidgets.QApplication.translate("ControlMakerWin", "World", None, -1))
        self.orientation_CB.setItemText(1, QtWidgets.QApplication.translate("ControlMakerWin", "Object", None, -1))
        self.rotationAxis_LB.setText(QtWidgets.QApplication.translate("ControlMakerWin", "Axis :", None, -1))
        self.rotationAxis_CB.setItemText(0, QtWidgets.QApplication.translate("ControlMakerWin", "X", None, -1))
        self.rotationAxis_CB.setItemText(1, QtWidgets.QApplication.translate("ControlMakerWin", "Y", None, -1))
        self.rotationAxis_CB.setItemText(2, QtWidgets.QApplication.translate("ControlMakerWin", "Z", None, -1))
        self.rotationValue_LB.setText(QtWidgets.QApplication.translate("ControlMakerWin", "Value :", None, -1))
        self.rotationReverse_CB.setText(QtWidgets.QApplication.translate("ControlMakerWin", "Reverse", None, -1))
        self.rotationPivot_LB.setText(QtWidgets.QApplication.translate("ControlMakerWin", "Pivot", None, -1))
        self.rotationPivot_CB.setItemText(0, QtWidgets.QApplication.translate("ControlMakerWin", "Transform", None, -1))
        self.rotationPivot_CB.setItemText(1, QtWidgets.QApplication.translate("ControlMakerWin", "Object", None, -1))
        self.rotation_BN.setText(QtWidgets.QApplication.translate("ControlMakerWin", "Rotate", None, -1))
        self.scale_GB.setTitle(QtWidgets.QApplication.translate("ControlMakerWin", "SCALE", None, -1))
        self.scalePivot_LB.setText(QtWidgets.QApplication.translate("ControlMakerWin", "Pivot:", None, -1))
        self.scalePivot_CB.setItemText(0, QtWidgets.QApplication.translate("ControlMakerWin", "Transform", None, -1))
        self.scalePivot_CB.setItemText(1, QtWidgets.QApplication.translate("ControlMakerWin", "Object", None, -1))
        self.sacleValue_LB.setText(QtWidgets.QApplication.translate("ControlMakerWin", "Value :", None, -1))
        self.scaleReverse_CB.setText(QtWidgets.QApplication.translate("ControlMakerWin", "Reverse", None, -1))
        self.scaleAxis_LB.setText(QtWidgets.QApplication.translate("ControlMakerWin", "Axis :", None, -1))
        self.scaleX_CB.setText(QtWidgets.QApplication.translate("ControlMakerWin", "X", None, -1))
        self.scaleY_CB.setText(QtWidgets.QApplication.translate("ControlMakerWin", "Y", None, -1))
        self.scaleZ_CB.setText(QtWidgets.QApplication.translate("ControlMakerWin", "Z", None, -1))
        self.scale_BN.setText(QtWidgets.QApplication.translate("ControlMakerWin", "Scale", None, -1))
        self.mirror_GB.setTitle(QtWidgets.QApplication.translate("ControlMakerWin", "MIRROR", None, -1))
        self.search_LB.setText(QtWidgets.QApplication.translate("ControlMakerWin", "Search for", None, -1))
        self.search_LE.setText(QtWidgets.QApplication.translate("ControlMakerWin", "Left", None, -1))
        self.replace_LB.setText(QtWidgets.QApplication.translate("ControlMakerWin", "Replace with", None, -1))
        self.replace_LE.setText(QtWidgets.QApplication.translate("ControlMakerWin", "Right", None, -1))
        self.mirror_BN.setText(QtWidgets.QApplication.translate("ControlMakerWin", "Mirror", None, -1))

